### ISSUE TITLE
Integrate Simulation Builder from Hoverfly Cloud?

### ISSUE THREAD

**Issue by zegerhoogeboom** [SpectoLabs/hoverfly-ui#20]
I'm using Hoverfly and was actually looking for exactly what you announced on [your blog](https://specto.io/blog/2017/11/14/announcing-api-simulation-builder-on-hoverfly-cloud/), a simulation editor/builder. Instead of creating a virtualized API run by you on the cloud version I'd like it to just export the JSON file. Alternatively it would be even cooler if it is possible to select simulations to become active (i.e. to basically run `hoverctl stop; hoverctl start; hoverctl import ${my_simulation}`). 

Any chance of anything in this direction happening? Just letting you know what I as a user would like and just curious on your semi-near-future roadmap.

**Comment by tommysitu** [comment]
HI @zegerhoogeboom as the question is related to our commercial product, could you fill out our contact form https://specto.io/contact/ so that we can get back to you? Thanks!

**Comment by zegerhoogeboom** [comment]
Hi @tommysitu, I see, I did mean "integrate into the open source `hoverfly-ui`" so figured this would be a fitting place, but will do!
